Repository liblouis/liblouis, pull requests merged in 2018-08, with the labels that each got.

#612 Add Chinese mandarin Braille code (Grade 1) and (Grade 2)
  extra/generate-display-names/display-names
  tables/Makefile.am
  tables/zh_CHN.tbl
  tables/zh_HK.tbl
  tables/zh_TW.tbl
  tables/zhcn-g1.ctb
  tables/zhcn-g2.ctb
  tests/Makefile.am
  tests/braille-specs/Makefile.am
  tests/braille-specs/zh-chn.yaml
  tests/braille-specs/zh-tw.yaml
  tests/braille-specs/zhcn-g1.yaml
  tests/braille-specs/zhcn-g2.yaml
Labels: tables

#619 Enable automake to generate dependencies for libbrlcheck.la
  tools/Makefile.am
Labels: build system

#625 Remove scripting language pass compiler
  NEWS
  liblouis/compileTranslationTable.c
Labels: cleanup/refactoring

#433 UEB fixes
  liblouis/compileTranslationTable.c
  liblouis/liblouis.h.in
  tables/en-ueb-g2.ctb
  tests/braille-specs/en-ueb-g2-dictionary_harness.yaml
Labels: waiting for feedback
