Repository liblouis/liblouis, pull requests merged in 2018-05, with the labels that each got.

#576 Document output value of inlen
  doc/liblouis.texi
Labels: documentation

#577 Update zh-tw.ctb to Version 2018-05
  tables/zh-tw.ctb
Labels: tables

#587 Fix yet another buffer overflow in the braille table parser
  liblouis/compileTranslationTable.c
Labels: buffer overflow
