Repository liblouis/liblouis, pull requests merged in 2019-11, with the labels that each got.

#847 Remove explicit detection of pkg-config
  configure.ac
Labels: build system

#855 Avoid a memory leak when several tables are specified with some of them that can't be resolved
  liblouis/compileTranslationTable.c
Labels: fixup

#857 Python bindings: uses the appropriate encoding to encode/decode paths
  python/louis/__init__.py.in
Labels: Python

#864 Eliminate some global variables
  liblouis/compileTranslationTable.c
  liblouis/internal.h
Labels: cleanup/refactoring

#827 Further separate display from translation
  liblouis/compileTranslationTable.c
  liblouis/internal.h
  liblouis/liblouis.h.in
  liblouis/lou_backTranslateString.c
  liblouis/lou_translateString.c
  liblouis/maketable.c
  tests/braille-specs/da-dk-g18.yaml
  tests/braille-specs/fr-bfu-comp6.yaml
  tests/braille-specs/fr-bfu-g2.yaml
  tests/braille-specs/no_harness.yaml
  tests/braille-specs/zh-tw.yaml
  tests/charToFallbackDots.c
  tests/getTable.c
  tests/yaml/Makefile.am
  tests/yaml/multipass-vs-match.yaml
  tests/yaml/multipass-vs-match_common.uti
  tools/brl_checks.c
  tools/brl_checks.h
  tools/lou_allround.c
  tools/lou_checkyaml.c
  tools/lou_debug.c
  tools/lou_maketable.d/utils.py
  tools/lou_trace.c
Labels: enhancement, test framework

#835 Punctuation corrections in Ethiopic Braille
  tables/ethio-g1.ctb
  tests/braille-specs/ethio-g1_harness.yaml
Labels: needs news, tables

#859 Add missing header to build with uClibc as C Library
  tools/lou_compare.c
Labels: build system

#872 Remove the second, undocumented argument to lou_translate
  tools/lou_translate.c
Labels: cleanup/refactoring

#873 Dutch 8 dot braille table draft
  NEWS
  tables/Makefile.am
  tables/nl-comp8.utb
  tests/Makefile.am
  tests/braille-specs/Makefile.am
  tests/braille-specs/nl-comp8_harness.yaml
Labels: tables

#851 Move lou_compare to tests and rename to compare_ueb_test_data
  .gitignore
  tests/Makefile.am
  tests/check_ueb_test_data.c
  tests/ueb_test_data.pl
  tools/Makefile.am
Labels: cleanup/refactoring, on hold

#871 Fixes to Norwegian Liblouis' 8dot braille
  NEWS
  tables/no-no-8dot.utb
  tests/braille-specs/no_8dot_harness.yaml
Labels: tables
