Repository liblouis/liblouis, pull requests merged in 2021-04, with the labels that each got.

#1067 Add documentation for begcomp and endcomp again
  doc/liblouis.texi
Labels: documentation

#1066 Major update to grade 2 Afrikaans table thanks to Christo de Klerk
  AUTHORS
  NEWS
  tables/afr-za-g2.ctb
  tests/braille-specs/afr-za-g2.yaml
Labels: tables

#1068 Github workflow to run metadata test
  .github/workflows/main.yml
Labels: build system

#1065 Various fixes to lou_trace
  liblouis/lou_translateString.c
  tools/lou_trace.c
Labels: bug, enhancement
