Repository liblouis/liblouis, pull requests merged in 2021-02, with the labels that each got.

#1042 Add a Python example how to translate html
  python/examples/translate-html.py
Labels: documentation

#953 Fix documentation of "caps" opcodes
  doc/liblouis.texi
  tests/yaml/capitalization.yaml
Labels: documentation, wip

#1044 Various fixes to Polish tables
  AUTHORS
  tables/Pl-Pl-g1.utb
  tables/pl-pl-comp8.ctb
  tests/Makefile.am
  tests/braille-specs/Makefile.am
  tests/braille-specs/Pl-Pl-g1_backward.yaml
  tests/braille-specs/Pl-Pl-g1_harness.yaml
  tests/braille-specs/pl-g1.yaml
  tests/braille-specs/pl-pl-comp8_harness.yaml
Labels: needs news

#1041 Update the Russian and Ukrainian tables
  NEWS
  tables/ru-litbrl-detailed.utb
  tables/ru-litbrl.ctb
  tables/uk.utb
  tests/braille-specs/ru.yaml
Labels: tables
