Repository liblouis/liblouis, pull requests merged in 2022-04, with the labels that each got.

#1201 Fix in NL table for N with tilde (Ñ)
  tables/nl-NL-g0.utb
  tests/braille-specs/nl-g0_harness.yaml
Labels: tables, needs news

#1205 Enable emscriptem workflow
  .github/workflows/emscripten.yml
  .github/workflows/scripts/emscripten-build.sh
Labels: build system

#1206 CI: allow manual triggers
  .github/workflows/check-format.yml
  .github/workflows/check-table-license.yml
  .github/workflows/emscripten.yml
  .github/workflows/macro.yml
  .github/workflows/main.yml
  .github/workflows/metadata.yml
  .github/workflows/mingw.yml
  .github/workflows/sanitizer.yml
Labels: build system

#1194 noCompbrlAhead: avoid overflowing input->chars
  liblouis/lou_translateString.c
Labels: memory error

#1195 typeform test: avoid oversized input buffer size
  tests/typeform.c
Labels: memory error
