Repository liblouis/liblouis, pull requests merged in 2022-11, with the labels that each got.

#1258 Tables/swahili
  AUTHORS
  NEWS
  extra/generate-display-names/display-names
  tables/Makefile.am
  tables/sw-ke-g1-2.ctb
  tables/sw-ke-g1-3.ctb
  tables/sw-ke-g1-4.ctb
  tables/sw-ke-g1-5.ctb
  tables/sw-ke-g1.utb
  tables/sw-ke-g2.ctb
  tests/Makefile.am
  tests/braille-specs/Makefile.am
  tests/braille-specs/sw-ke-dictionary.yaml
  tests/braille-specs/sw-ke.yaml
Labels: tables

#1262 CI: add CIFuzz integration
  .github/workflows/cifuzz.yml
Labels: build system

#1263 Fix wrong pointer to integer conversions
  liblouis/lou_translateString.c
Labels: bug

#1266 Update zh-tw.ctb to version 2022-12
  NEWS
  extra/generate-display-names/display-names
  tables/Makefile.am
  tables/zh-tw.ctb
  tables/zh_TW.tbl
  tests/braille-specs/Makefile.am
  tests/braille-specs/zh-tw-dictionary.yaml
  tests/braille-specs/zh-tw.yaml
Labels: tables

#1270 Fix metadata check
  extra/generate-display-names/Makefile
  extra/generate-display-names/go.mod
Labels: build system
