Repository liblouis/liblouis, pull requests merged in 2023-02, with the labels that each got.

#1302 Check filename before coping to initialLogFileName
  liblouis/logging.c
Labels: bug, memory error, needs news

#1300 Check the path length before coping into tableFile
  liblouis/compileTranslationTable.c
Labels: memory error, needs news

#1307 Fix class operator code deprecation warnings in tables/bg.utb
  tables/bg.utb
Labels: needs news

#1295 tables/spaces.uti: Fixed typos and two broken replacement rules
  tables/spaces.uti
  tests/braille-specs/spaces.yaml
  tools/lou_checkyaml.c
Labels: needs news

#1312 Added few new elements and new testcases into tables/hyph_hu_HU.dic
  tables/hyph_hu_HU.dic
  tests/braille-specs/hu-hu-g1-hyph_harness.yaml
Labels: needs news

#1308 Rename all occurrences of liblouis.org to liblouis.io
  HACKING
  README
  configure.ac
  tables/en-us-comp6.ctb
  tables/en-us-compbrl.uti
  tables/ga-g1.utb
  tables/ga-g2.ctb
  tables/grc-international-en.utb
  tables/haw-us-g1.ctb
  tables/he-IL-comp8.utb
  tables/he-IL.utb
  tables/ka.utb
  tables/km-g1.utb
  tables/mao-nz-g1.ctb
  tables/nl-NL-g0.utb
  tables/nl-chardefs.uti
  tables/nl-comp8.utb
  tables/no-no-8dot-fallback-6dot-g0.utb
  tables/no-no-8dot.utb
  tables/no-no-g0.utb
  tables/no-no-g1.ctb
  tables/no-no-g2.ctb
  tables/no-no-g3.ctb
  tables/pl.tbl
  tables/ru-litbrl-detailed.utb
  tables/ru-litbrl.ctb
  tables/sah.utb
  tables/sk-g1.ctb
  tables/sl-si-g1.utb
  tables/sw-ke-g1-2.ctb
  tables/sw-ke-g1-3.ctb
  tables/sw-ke-g1-4.ctb
  tables/sw-ke-g1-5.ctb
  tables/sw-ke-g1.utb
  tables/sw-ke-g2.ctb
  tables/tt.utb
  tables/wordcx.dis
  tests/braille-specs/afr-za-g2.yaml
  tests/braille-specs/en-us-comp6.yaml
  tests/braille-specs/ga-g1_harness.yaml
  tests/braille-specs/ga-g2_harness.yaml
  tests/braille-specs/he-IL.yaml
  tests/braille-specs/lv_harness.yaml
  tests/braille-specs/nl-comp8_harness.yaml
  tests/braille-specs/nl-g0_harness.yaml
  tests/braille-specs/pl-g1.yaml
  tests/braille-specs/ru.yaml
  tests/braille-specs/sah.yaml
  tests/braille-specs/sl-g1.yaml
  tests/braille-specs/st-g2.yaml
  tests/braille-specs/tt.yaml
  tests/braille-specs/ve-g2.yaml
  tests/braille-specs/xh-g2.yaml
Labels: needs news

#1314 NL Comp8 braille 2022 update
  NEWS
  tables/nl-comp8.utb
  tests/braille-specs/nl-comp8_harness.yaml
Labels: tables
