Repository liblouis/liblouis, pull requests merged in 2023-05, with the labels that each got.

#1351 Fix out-of-bound write in brl_checks.c
  tools/brl_checks.c
Labels: memory error, needs news

#1368 Make sure all opcodes and comments start at the beginning of the line
  tables/da-dk-g16-lit_1993.ctb
  tables/da-dk-g16.ctb
  tables/da-dk-g16_1993.ctb
  tables/da-dk-g26-lit_1993.ctb
  tables/da-dk-g26.ctb
  tables/da-dk-g26_1993.ctb
  tables/da-dk-g26l-lit_1993.ctb
  tables/da-dk-g26l_1993.ctb
  tables/de-de.dis
  tables/kannada.cti
  tables/km-g1.utb
Labels: cleanup

#1372 tests: fuzzing: add fuzzer for backTranslate logic
  tests/fuzzing/build.sh
  tests/fuzzing/fuzz_backtranslate.c
Labels: fuzzing
