Repository liblouis/liblouis, pull requests merged in 2024-10, with the labels that each got.

#1638 Update liblouis.texi
  doc/liblouis.texi
Labels: documentation, needs news

#1640 Dutch: add virtual dot to DAGGER
  tables/nl-BE.dis
  tables/nl-chardefs.uti.in
  tables/nl-print.dis
  tables/nl-unicode.dis
  tests/braille-specs/nl-g0_harness.yaml
Labels: tables

#1641 Update liblouis.texi
  doc/liblouis.texi
Labels: documentation
