Repository liblouis/liblouis, pull requests merged in 2025-05, with the labels that each got.

#1773 Fix incorrect links
  doc/liblouis.texi
Labels: documentation, needs news

#1774 Add --enable-macos-universal-binary configuration option
  configure.ac
  gnulib/Makefile.am
  liblouis/Makefile.am
  tools/Makefile.am
  tools/gnulib/Makefile.am
Labels: build system

#1746 Fix metadata of Russian 6-dot computer braille table
  .github/workflows/fuzzing.yml
  NEWS
  extra/generate-display-names/display-names
  tables/Makefile.am
  tables/bel-comp.utb
  tables/ru-comp6.utb
  tables/ru-comp8.utb
  tables/uk-comp.utb
  tests/braille-specs/ba.yaml
  tests/braille-specs/ru.yaml
  tests/braille-specs/spaces.yaml
Labels: tables, needs news
