Repository liblouis/liblouis, pull requests merged in 2025-02, with the labels that each got.

#1727 Norwegian: don't use permanent cap sign in words with mixed case
  tables/no-no-g0.utb
  tests/braille-specs/no.yaml
Labels: tables, needs news

#1703 Fix default table search path on Windows
  liblouis/compileTranslationTable.c
Labels: needs news

#1673 Make value in table metadata field mandatory
  doc/liblouis.texi
  liblouis/metadata.c
  tools/lou_translate.c
Labels: needs news, backward-incompatible

#1710 Fix free error in parseQuery and analyzeTable
  liblouis/metadata.c
Labels: memory error, needs news

#1734 Return from finalizeCharacter if a recursive invocation failed
  liblouis/compileTranslationTable.c
Labels: needs news

#1724 Norwegian extend
  tables/no-no-chardefs6.uti
  tables/no-no-comp8.ctb
  tables/no-no-g0.utb
  tables/no-no-latinLetterDef6Dots_diacritics.uti
  tests/Makefile.am
  tests/braille-specs/Makefile.am
  tests/braille-specs/no.yaml
  tests/braille-specs/no_8dot_harness.yaml
  tests/braille-specs/spaces.yaml
Labels: tables, needs news
